import React, { useState } from 'react'
import { useWallet } from '@solana/wallet-adapter-react'
import { WalletMultiButton } from '@solana/wallet-adapter-react-ui'
import { PriceChart }      from './components/PriceChart.jsx'
import { OrderPanel }      from './components/OrderPanel.jsx'
import { PositionsTable }  from './components/PositionsTable.jsx'

const MARKETS = ['SOL-PERP', 'BTC-PERP', 'ETH-PERP']

export function App() {
  const { publicKey }       = useWallet()
    const [market, setMarket] = useState('SOL-PERP')
      const [tab, setTab]       = useState('TRADE')

        const shortKey = publicKey
            ? publicKey.toBase58().slice(0, 4) + '…' + publicKey.toBase58().slice(-4)
                : null

                  return (
                      <div style={styles.root}>
                            <div style={styles.gridBg} />

                                  <header style={styles.header}>
                                          <div style={styles.logo}>
                                                    PrivPerps
                                                              <span style={styles.logoBadge}>BETA</span>
                                                                      </div>
                                                                              <span style={styles.arciumTag}>⬡ ARCIUM MPC</span>
                                                                                      <nav style={styles.nav}>
                                                                                                {['TRADE','PORTFOLIO'].map(t => (
                                                                                                            <button
                                                                                                                          key={t}
                                                                                                                                        onClick={() => setTab(t)}
                                                                                                                                                      style={{ ...styles.navBtn, ...(tab === t ? styles.navActive : {}) }}
                                                                                                                                                                  >
                                                                                                                                                                                {t}
                                                                                                                                                                                            </button>
                                                                                                                                                                                                      ))}
                                                                                                                                                                                                              </nav>
                                                                                                                                                                                                                      <div style={styles.walletWrap}>
                                                                                                                                                                                                                                <WalletMultiButton />
                                                                                                                                                                                                                                          {publicKey && <span style={styles.keyBadge}>◎ {shortKey}</span>}
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                        </header>

                                                                                                                                                                                                                                                              <div style={styles.marketBar}>
                                                                                                                                                                                                                                                                      {MARKETS.map(m => (
                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                            key={m}
                                                                                                                                                                                                                                                                                                        onClick={() => setMarket(m)}
                                                                                                                                                                                                                                                                                                                    style={{ ...styles.marketBtn, ...(market === m ? styles.marketActive : {}) }}
                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                          {m}
                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                    <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 7,
                                                                                                                                                                                                                                                                                                                                                                                          background: 'rgba(91,79,255,0.1)', border: '1px solid rgba(91,79,255,0.3)',
                                                                                                                                                                                                                                                                                                                                                                                                                padding: '5px 14px', borderRadius: 20, fontSize: 11, color: 'var(--accent)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{ width: 7, height: 7, background: 'var(--accent2)', borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                   display: 'inline-block', animation: 'pulse 2s infinite' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                             POSITIONS ENCRYPTED
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div style={styles.main}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div style={styles.left}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <PriceChart market={market} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <PositionsTable />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <OrderPanel market={market} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div style={styles.networkBadge}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ◉ DEVNET — switch to mainnet-beta in WalletProvider.jsx when ready
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               root:        { display: 'flex', flexDirection: 'column', height: '100vh',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                overflow: 'hidden', position: 'relative' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  gridBg:      { position: 'fixed', inset: 0, pointerEvents: 'none', zIndex: 0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   backgroundImage:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      'linear-gradient(rgba(91,79,255,0.03) 1px, transparent 1px),' +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'linear-gradient(90deg, rgba(91,79,255,0.03) 1px, transparent 1px)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backgroundSize: '40px 40px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            header:      { position: 'relative', zIndex: 10, height: 56,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             background: 'rgba(4,5,10,0.9)', backdropFilter: 'blur(12px)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderBottom: '1px solid var(--border)', display: 'flex',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               alignItems: 'center', padding: '0 24px', gap: 20, flexShrink: 0 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 logo:        { fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  letterSpacing: '-0.5px', display: 'flex', alignItems: 'center', gap: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    logoBadge:   { background: 'var(--accent)', color: '#fff', fontSize: 9,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     fontFamily: 'var(--font-mono)', padding: '2px 6px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 3, letterSpacing: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        arciumTag:   { fontSize: 11, color: 'var(--accent2)', letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         border: '1px solid rgba(0,229,192,0.2)', padding: '3px 8px', borderRadius: 3 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           nav:         { display: 'flex', gap: 2, marginLeft: 'auto' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             navBtn:      { background: 'none', border: 'none', color: 'var(--muted)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fontFamily: 'var(--font-mono)', fontSize: 12, padding: '6px 14px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               cursor: 'pointer', borderRadius: 4, letterSpacing: 1, transition: 'all 0.15s' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 navActive:   { color: 'var(--text)', background: 'var(--surface2)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   walletWrap:  { display: 'flex', alignItems: 'center', gap: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     keyBadge:    { fontSize: 11, color: 'var(--accent2)', letterSpacing: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       marketBar:   { position: 'relative', zIndex: 9, display: 'flex', alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        gap: 2, background: 'var(--surface)', borderBottom: '1px solid var(--border)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         padding: '0 20px', flexShrink: 0, overflowX: 'auto' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           marketBtn:   { background: 'none', border: 'none', color: 'var(--muted)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontFamily: 'var(--font-mono)', fontSize: 12, padding: '12px 16px',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cursor: 'pointer', letterSpacing: 1, borderBottom: '2px solid transparent',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              transition: 'all 0.15s', whiteSpace: 'nowrap' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marketActive:{ color: 'var(--text)', borderBottomColor: 'var(--accent)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  main:        { display: 'grid', gridTemplateColumns: '1fr 320px', flex: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   overflow: 'hidden', position: 'relative', zIndex: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     left:        { display: 'flex', flexDirection: 'column', overflow: 'hidden',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRight: '1px solid var(--border)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        networkBadge:{ position: 'fixed', bottom: 10, left: '50%', transform: 'translateX(-50%)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         fontSize: 9, color: 'var(--muted)', letterSpacing: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          background: 'rgba(4,5,10,0.8)', padding: '4px 12px', borderRadius: 10,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           border: '1px solid var(--border)', zIndex: 100 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }