import React, { useEffect, useRef, useState } from 'react'

function generateWalk(points = 80, start = 148, vol = 0.8) {
  const data = []
    let p = start
      for (let i = 0; i < points; i++) {
          p += (Math.random() - 0.48) * vol
              data.push(parseFloat(p.toFixed(2)))
                }
                  return data
                  }

                  export function PriceChart({ market }) {
                    const canvasRef = useRef(null)
                      const dataRef   = useRef(generateWalk())
                        const [price, setPrice]   = useState(dataRef.current.at(-1))
                          const [change, setChange] = useState('+2.41')

                            useEffect(() => {
                                const canvas = canvasRef.current
                                    if (!canvas) return

                                        const draw = () => {
                                              const ctx  = canvas.getContext('2d')
                                                    const W    = canvas.offsetWidth
                                                          const H    = canvas.offsetHeight
                                                                canvas.width  = W
                                                                      canvas.height = H

                                                                            const data = dataRef.current
                                                                                  const min  = Math.min(...data) - 0.5
                                                                                        const max  = Math.max(...data) + 0.5
                                                                                              const xStep = W / (data.length - 1)
                                                                                                    const toY = v => H - ((v - min) / (max - min)) * H * 0.85 - H * 0.05

                                                                                                          ctx.strokeStyle = 'rgba(30,34,64,0.6)'
                                                                                                                ctx.lineWidth = 1
                                                                                                                      for (let i = 0; i <= 4; i++) {
                                                                                                                              const y = (H / 4) * i
                                                                                                                                      ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke()
                                                                                                                                            }

                                                                                                                                                  const grad = ctx.createLinearGradient(0, 0, 0, H)
                                                                                                                                                        grad.addColorStop(0,   'rgba(91,79,255,0.25)')
                                                                                                                                                              grad.addColorStop(0.6, 'rgba(91,79,255,0.05)')
                                                                                                                                                                    grad.addColorStop(1,   'rgba(91,79,255,0)')

                                                                                                                                                                          ctx.beginPath()
                                                                                                                                                                                data.forEach((v, i) => {
                                                                                                                                                                                        if (i === 0) ctx.moveTo(0, toY(v))
                                                                                                                                                                                                else ctx.lineTo(i * xStep, toY(v))
                                                                                                                                                                                                      })
                                                                                                                                                                                                            ctx.lineTo(W, H); ctx.lineTo(0, H); ctx.closePath()
                                                                                                                                                                                                                  ctx.fillStyle = grad
                                                                                                                                                                                                                        ctx.fill()

                                                                                                                                                                                                                              ctx.beginPath()
                                                                                                                                                                                                                                    ctx.strokeStyle = '#5b4fff'
                                                                                                                                                                                                                                          ctx.lineWidth   = 2
                                                                                                                                                                                                                                                ctx.lineJoin    = 'round'
                                                                                                                                                                                                                                                      data.forEach((v, i) => {
                                                                                                                                                                                                                                                              if (i === 0) ctx.moveTo(0, toY(v))
                                                                                                                                                                                                                                                                      else ctx.lineTo(i * xStep, toY(v))
                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                  ctx.stroke()

                                                                                                                                                                                                                                                                                        const lastX = (data.length - 1) * xStep
                                                                                                                                                                                                                                                                                              const lastY = toY(data.at(-1))
                                                                                                                                                                                                                                                                                                    ctx.beginPath()
                                                                                                                                                                                                                                                                                                          ctx.arc(lastX, lastY, 4, 0, Math.PI * 2)
                                                                                                                                                                                                                                                                                                                ctx.fillStyle = '#5b4fff'
                                                                                                                                                                                                                                                                                                                      ctx.fill()
                                                                                                                                                                                                                                                                                                                            ctx.beginPath()
                                                                                                                                                                                                                                                                                                                                  ctx.arc(lastX, lastY, 8, 0, Math.PI * 2)
                                                                                                                                                                                                                                                                                                                                        ctx.fillStyle = 'rgba(91,79,255,0.2)'
                                                                                                                                                                                                                                                                                                                                              ctx.fill()
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                      draw()
                                                                                                                                                                                                                                                                                                                                                          const ro = new ResizeObserver(draw)
                                                                                                                                                                                                                                                                                                                                                              ro.observe(canvas)
                                                                                                                                                                                                                                                                                                                                                                  return () => ro.disconnect()
                                                                                                                                                                                                                                                                                                                                                                    }, [price])

                                                                                                                                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                                                                                                                                          const id = setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                const last = dataRef.current.at(-1)
                                                                                                                                                                                                                                                                                                                                                                                      const next = parseFloat((last + (Math.random() - 0.48) * 0.5).toFixed(2))
                                                                                                                                                                                                                                                                                                                                                                                            dataRef.current = [...dataRef.current.slice(1), next]
                                                                                                                                                                                                                                                                                                                                                                                                  const base = dataRef.current[0]
                                                                                                                                                                                                                                                                                                                                                                                                        const pct  = (((next - base) / base) * 100).toFixed(2)
                                                                                                                                                                                                                                                                                                                                                                                                              setPrice(next)
                                                                                                                                                                                                                                                                                                                                                                                                                    setChange(pct)
                                                                                                                                                                                                                                                                                                                                                                                                                        }, 1500)
                                                                                                                                                                                                                                                                                                                                                                                                                            return () => clearInterval(id)
                                                                                                                                                                                                                                                                                                                                                                                                                              }, [])

                                                                                                                                                                                                                                                                                                                                                                                                                                const isUp = parseFloat(change) >= 0

                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={styles.wrap}>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={styles.header}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={styles.pairRow}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <span style={styles.pair}>{market}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{ ...styles.livePrice, color: isUp ? 'var(--green)' : 'var(--red)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ${price.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ...styles.chip,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                background: isUp ? 'rgba(0,229,160,0.1)' : 'rgba(255,79,123,0.1)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: isUp ? 'var(--green)' : 'var(--red)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {isUp ? '+' : ''}{change}%
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div style={styles.stats}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {[
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ['24H VOL',  '$842.3M'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ['OPEN INT', '$213.7M'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ['FUNDING',  '+0.0012%'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ['INDEX',    `$${price.toFixed(2)}`],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ].map(([label, val]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div key={label} style={styles.stat}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={styles.statLabel}>{label}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <span style={styles.statVal}>{val}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={styles.privacyPill}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={styles.dot} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                MPC ACTIVE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <canvas ref={canvasRef} style={styles.canvas} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      wrap:        { display: 'flex', flexDirection: 'column',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       background: 'var(--surface)', flex: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         header:      { padding: '14px 20px', borderBottom: '1px solid var(--border)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           pairRow:     { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 10 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             pair:        { fontFamily: 'var(--font-display)', fontWeight: 800, fontSize: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               livePrice:   { fontFamily: 'var(--font-mono)', fontSize: 22, fontWeight: 700 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 chip:        { fontSize: 11, padding: '3px 8px', borderRadius: 3 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   stats:       { display: 'flex', gap: 24, alignItems: 'center', flexWrap: 'wrap' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     stat:        { display: 'flex', flexDirection: 'column', gap: 2 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       statLabel:   { fontSize: 9, color: 'var(--muted)', letterSpacing: '1.5px' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         statVal:     { fontSize: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           privacyPill: { marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 7,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            background: 'rgba(91,79,255,0.1)', border: '1px solid rgba(91,79,255,0.3)',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             padding: '5px 12px', borderRadius: 20, fontSize: 11, color: 'var(--accent)' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               dot:         { width: 7, height: 7, background: 'var(--accent2)', borderRadius: '50%',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                animation: 'pulse 2s infinite', display: 'inline-block' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  canvas:      { flex: 1, minHeight: 260, display: 'block', width: '100%' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }